### ISSUE TITLE
Broken on 1.16.4

### ISSUE THREAD

**Issue by cpw** [TechnicianLP/ReAuth#32]
About the only mod that breaks on 1.16.4. Heh.

```
Caused by: java.lang.NoSuchMethodError: 'void com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication.<init>(com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService, com.mojang.authlib.Agent)'
	at technicianlp.reauth.AuthHelper.<init>(AuthHelper.java:81) ~[reauth:3.9.2] {re:classloading}
	at technicianlp.reauth.ReAuth.<clinit>(ReAuth.java:31) ~[reauth:3.9.2] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:427) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:35.0] {re:classloading}
	at jdk.internal.reflect.GeneratedConstructorAccessor44.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[forge:35.0] {re:classloading}
```

**Comment by TechnicianLP** [comment]
Yes im likely the only one this change affects; Nothing that cant be fixed with a bit of reflection magic though.
A fix for 1.16.4 has been incorporated into the Forge and Fabric versions - Thanks for the report.

This will likely break again once the Microsoft merge starts :(
