### ISSUE TITLE
1.18.2 - 4.0.6 - Error 404

### ISSUE THREAD

**Issue by Shark3900** [TechnicianLP/ReAuth#54]
Hello!

I've been attempting to play Stoneblock 3 with ReAuth.
I was having the IPv6 issue mentioned in recent reports, so I updated to 4.0.6.

Good news: Whenever I try to authenticate, the browser says it was successful.
Bad news: None of my actual login attempts ever succeed, with the log file always producing the same result:

```
[17:21:36] [ReAuth-3/INFO]: Starting local endpoint
[17:21:36] [ReAuth-3/INFO]: Started local endpoint
[17:21:36] [ReAuth-3/INFO]: Waiting for Authentication
[17:21:39] [ReAuth-3/INFO]: Received Microsoft Authentication Code
[17:21:39] [ReAuth-1/INFO]: About to stop local endpoint
[17:21:39] [ReAuth-2/INFO]: Authenticating with Microsoft
[17:21:40] [ReAuth-3/INFO]: Authenticating with Xbox Live
[17:21:40] [ReAuth-2/INFO]: Authenticating with XSTS
[17:21:40] [ReAuth-1/INFO]: Stopping local endpoint
[17:21:40] [ReAuth-3/INFO]: Authenticating with Mojang
[17:21:40] [ReAuth-2/INFO]: Retrieving Profile
[17:21:40] [ReAuth-2/INFO]: Login failed
[17:21:40] [ReAuth-2/ERROR]: Login failed
java.util.concurrent.CompletionException: technicianlp.reauth.authentication.http.InvalidResponseException: Error received with code 404: NOT_FOUND
	at technicianlp.reauth.authentication.flows.impl.util.AuthFunction.apply(AuthFunction.java:24) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.flows.impl.FlowBase.lambda$wrapStep$2(FlowBase.java:96) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: technicianlp.reauth.authentication.http.InvalidResponseException: Error received with code 404: NOT_FOUND
	at technicianlp.reauth.authentication.http.Response.get(Response.java:32) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.http.HttpUtil.performGetRequest(HttpUtil.java:59) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.MsAuthAPI.fetchProfile(MsAuthAPI.java:89) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.flows.impl.util.AuthFunction.apply(AuthFunction.java:22) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	... 6 more
[17:21:41] [ReAuth-1/INFO]: Stopped local endpoint
```

This occurs with both the local device and all devices methods and with numerous attempts in each:

```
[17:30:19] [ReAuth-3/INFO]: Requesting Device Code from Microsoft
[17:30:20] [ReAuth-2/INFO]: Starting to poll Microsoft for token
[17:30:48] [ReAuth-2/INFO]: Authorization received
[17:30:48] [ReAuth-3/INFO]: Authenticating with Xbox Live
[17:30:49] [ReAuth-2/INFO]: Authenticating with XSTS
[17:30:49] [ReAuth-3/INFO]: Authenticating with Mojang
[17:30:49] [ReAuth-2/INFO]: Retrieving Profile
[17:30:49] [ReAuth-2/INFO]: Login failed
[17:30:49] [ReAuth-2/ERROR]: Login failed
java.util.concurrent.CompletionException: technicianlp.reauth.authentication.http.InvalidResponseException: Error received with code 404: NOT_FOUND
	at technicianlp.reauth.authentication.flows.impl.util.AuthFunction.apply(AuthFunction.java:24) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.flows.impl.FlowBase.lambda$wrapStep$2(FlowBase.java:96) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: technicianlp.reauth.authentication.http.InvalidResponseException: Error received with code 404: NOT_FOUND
	at technicianlp.reauth.authentication.http.Response.get(Response.java:32) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.http.HttpUtil.performGetRequest(HttpUtil.java:59) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.MsAuthAPI.fetchProfile(MsAuthAPI.java:89) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.flows.impl.util.AuthFunction.apply(AuthFunction.java:22) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	... 6 more
[17:30:49] [ReAuth-2/ERROR]: Profile failed to save
java.util.concurrent.CompletionException: technicianlp.reauth.authentication.http.InvalidResponseException: Error received with code 404: NOT_FOUND
	at technicianlp.reauth.authentication.flows.impl.util.AuthFunction.apply(AuthFunction.java:24) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.flows.impl.FlowBase.lambda$wrapStep$2(FlowBase.java:96) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: technicianlp.reauth.authentication.http.InvalidResponseException: Error received with code 404: NOT_FOUND
	at technicianlp.reauth.authentication.http.Response.get(Response.java:32) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.http.HttpUtil.performGetRequest(HttpUtil.java:59) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.MsAuthAPI.fetchProfile(MsAuthAPI.java:89) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	at technicianlp.reauth.authentication.flows.impl.util.AuthFunction.apply(AuthFunction.java:22) ~[ReAuth-1.18-Forge-4.0.6.jar%23215!/:4.0.6]
	... 6 more
[17:30:58] [Render thread/INFO]: Stopping!
```

**Comment by TechnicianLP** [comment]
Please make sure to log into the correct Microsoft/Xbox account. 
It looks like there is no Minecraft Account associated with the Xbox-Account youre logging into.

**Comment by Shark3900** [comment]
Thanks for the quick response!

I do have the game with Game Pass, it seems this issue might be related to me using GDLauncher, as using the FTB Launcher appears not to have this issue. I assume by the Official Launcher you mean the default Minecraft Launcher?
