### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by st4xy** [TechnicianLP/ReAuth#67]
Since December 20, it has not been possible to log in using the "This Device" button. I checked on two versions of Minecraft, 1.19, 1.8.9. Disconnected VPN. reinstalled the client and the error does not go away. 24 hours ago everything worked.
![изображение](https://github.com/TechnicianLP/ReAuth/assets/154468095/f0bdde1a-2ab6-43b7-bd37-4aa6c45a1ba6)

**Comment by Twisted-Code** [comment]
I'm having the same problem. To quote my comment on the curseforge project:

As of recently, I've been getting "an unknown error occurred" when I try to authenticate using the "this device" option, no matter how many times I retry. Any idea what that's about?

The log says:
```
[01:49:14] [ReAuth-2/INFO] [ReAuth/]: Login failed
[01:49:14] [ReAuth-2/ERROR] [ReAuth/]: Login failed
java.util.concurrent.CompletionException: java.net.BindException: Address already in use: bind
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1294) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?] {re:mixin}
	at technicianlp.reauth.authentication.flows.impl.MicrosoftCodeFlow.lambda$new$0(MicrosoftCodeFlow.java:61) ~[ReAuth-1.19-Forge-4.0.7.jar%23827!/:4.0.7] {re:classloading}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] {}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?] {}
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?] {}
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?] {}
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?] {}
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89) ~[?:?] {}
	at sun.net.httpserver.ServerImpl.&lt;init&gt;(ServerImpl.java:142) ~[jdk.httpserver:?] {}
	at sun.net.httpserver.HttpServerImpl.&lt;init&gt;(HttpServerImpl.java:50) ~[jdk.httpserver:?] {}
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35) ~[jdk.httpserver:?] {}
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:150) ~[jdk.httpserver:?] {}
	at technicianlp.reauth.authentication.http.server.AuthenticationCodeServer.&lt;init&gt;(AuthenticationCodeServer.java:33) ~[ReAuth-1.19-Forge-4.0.7.jar%23827!/:4.0.7] {re:classloading}
	at technicianlp.reauth.authentication.flows.impl.MicrosoftCodeFlow.lambda$new$0(MicrosoftCodeFlow.java:58) ~[ReAuth-1.19-Forge-4.0.7.jar%23827!/:4.0.7] {re:classloading}
	... 3 more
Exception in thread "ReAuth-2" java.lang.NullPointerException: Cannot invoke "technicianlp.reauth.authentication.http.server.AuthenticationCodeServer.stop(boolean)" because "this.codeServer" is null
	at TRANSFORMER/reauth@4.0.7/technicianlp.reauth.authentication.flows.impl.MicrosoftCodeFlow.lambda$cancel$1(MicrosoftCodeFlow.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)


```

**Comment by TechnicianLP** [comment]
somthing is already using the port ReAuth is using to receive the Microsoft authentication. Please use the "Any Device" option for now.
